### PR TITLE
More verbosity on start and ca-certificates package

### PR DESCRIPTION
**Pull request by InAnimaTe**
I've added some simple echo statements so users know whats going on when the image starts (if they are attached/watching the log). This is especially helpful when checking to ensure a module builds.

Also, because I had to go through the painful process, I've added the ca-certificates package so servers with proper certificates will be connected to without a problem. I've added the necessary documentation about this 1.6 change and some links as well.

Lastly, I want to mention that docker image is awesome! Thanks a lot to jimeh for creating it!

### CODE REVIEW

**Comment by InAnimaTe** [comment]
Ohh, and just found out, having ca-certificates also enables the fantastic [znc-push](https://github.com/jreese/znc-push) plugin to actually work ;)

**Comment by andrealinux1** [comment]
I think that the installation of the **ca-certificates** package is a must. Please merge this PR so I do not have to manually build the image after having added this feature.

**Comment by InAnimaTe** [comment]
@andrealinux1 I forked and maintain my own [repo](https://github.com/InAnimaTe/docker-znc-1) with these fixes, as obviously, the maintainer doesn't have time to accept these.

**Comment by andrealinux1** [comment]
@InAnimaTe Thanks for the info, this will save me the effort of cloning the original repo and built it after having applied your patch:). Anyway I hope that @jimeh will have time to merge this PR when he will have time.

**Comment by jinpark** [comment]
+1 on the ca cert

**Pull request merged**
